### ISSUE TITLE
Maps throwing errors

### ISSUE THREAD

**Issue by curt2008** [tuttarealstep/PokeGOAPI-PHP#1]
Hey,

When attempting to use the newly implemented Maps module, I'm getting the following errors :

`Fatal error: Uncaught exception 'InvalidArgumentException' with message 'value must be a integer or float' in /home/username/public_html/PokeGOAPI-PHP-master/src/POGOProtos/protocolbuffers.inc.php:611 Stack trace: #0 /home/username/public_html/PokeGOAPI-PHP-master/src/POGOProtos/protocolbuffers.inc.php(637): Protobuf::encode_varint(Array) #1 /home/username/public_html/PokeGOAPI-PHP-master/src/POGOProtos/Networking/Requests/Messages/GetMapObjectsMessage.php(96): Protobuf::write_varint(Resource id #34, Array) #2 /home/username/public_html/PokeGOAPI-PHP-master/src/POGOProtos/protocolbuffers.inc.php(103): POGOProtos\Networking\Requests\Messages\GetMapObjectsMessage->write(Resource id #34) #3 /home/username/public_html/PokeGOAPI-PHP-master/src/PokemonGoAPI/Main/ServerRequest.php(23): ProtobufMessage->toProtobuf() #4 /home/username/public_html/PokeGOAPI-PHP-master/src/PokemonGoAPI/Api/Map/Map.php(142): PokemonGoAPI\Main\ServerRequest->__construct(106, Object(POGOProtos\Networking\Requests\Messages\GetMap in /home/username/public_html/PokeGOAPI-PHP-master/src/POGOProtos/protocolbuffers.inc.php on line 611`

That was right after doing these functions :

```
$PokemonGoAPI = new PokemonGoAPI($login);
$PokemonGoAPI->getOutput()->setPKGODEBUG(true);

$map = $PokemonGoAPI->getMap();
var_dump($map->getMapObjects(1));
die();`
```

**Comment by tuttarealstep** [comment]
Thanks for the report. Now I check what's wrong.

**Comment by tuttarealstep** [comment]
@curt2008 Fix with last commit!
![screen](https://cloud.githubusercontent.com/assets/2702557/17230558/14eee71a-551d-11e6-952b-2bf36b86e642.png)

**Comment by curt2008** [comment]
Works perfect for me also, may I ask how do we iterate through the "CatchablePokemon" and find the given Lat/Lng location & also the expiry time?

**Comment by curt2008** [comment]
It also appears that `["encounterId":"PokemonGoAPI\Api\Map\Pokemon\CatchablePokemon":private]=> NULL` is always returning NULL, any reason for this mate?

**Comment by tuttarealstep** [comment]
Are you sure always null? I've tried many times but always encounterId is not null.

![screen fix encounterid](https://cloud.githubusercontent.com/assets/2702557/17243429/117b4a50-557d-11e6-91d2-a2b97f5485d2.png)

**For iterate and get lat and location or expiry time**
If you go to src/PokemonGoAPI/Api/Map/Pokemon/CatchablePokemon.php you can find all function like:
getExpirationTimestampMs() or getLatitude() etc.

I'm building a guide with many examples, for now, I've uploaded a new commit with a new exampl: CatchPokemonAtAreaExample where I got for each pokemon its id.

**Comment by curt2008** [comment]
Perfect mate thankyou! It's because I always forgot to run the `$encResult = $CatchablePokemon->encounterPokemon();` call haha

**Comment by curt2008** [comment]
`["map":"PokemonGoAPI\Api\PokemonGoAPI":private]=>
    object(PokemonGoAPI\Api\Map\Map)#702 (5) {
      ["pokemonGoAPI":"PokemonGoAPI\Api\Map\Map":private]=>
      *RECURSION*
      ["useCache":"PokemonGoAPI\Api\Map\Map":private]=>
      bool(true)
      ["cachedMapObjects":"PokemonGoAPI\Api\Map\Map":private]=>
      object(PokemonGoAPI\Api\Map\MapObjects)#695 (9) {
        ["pokemonGoAPI":"PokemonGoAPI\Api\Map\MapObjects":private]=>
        *RECURSION*
        ["nearbyPokemons":"PokemonGoAPI\Api\Map\MapObjects":private]=>
        array(1) {
          [0]=>
          object(POGOProtos\Map\Pokemon\NearbyPokemon)#534 (5) {
            ["_unknown":"POGOProtos\Map\Pokemon\NearbyPokemon":private]=>
            NULL
            ["pokemonId":"POGOProtos\Map\Pokemon\NearbyPokemon":private]=>
            int(129)
            ["distanceInMeters":"POGOProtos\Map\Pokemon\NearbyPokemon":private]=>
            float(200)
            ["encounterId":"POGOProtos\Map\Pokemon\NearbyPokemon":private]=>
            NULL
            ["_unknown":"ProtobufMessage":private]=>
            NULL
          }
        }
        ["catchablePokemons":"PokemonGoAPI\Api\Map\MapObjects":private]=>
        array(1) {
          [0]=>
          object(POGOProtos\Map\Pokemon\MapPokemon)#570 (8) {
            ["_unknown":"POGOProtos\Map\Pokemon\MapPokemon":private]=>
            NULL
            ["spawnPointId":"POGOProtos\Map\Pokemon\MapPokemon":private]=>
            string(11) "2a32a170f4f"
            ["encounterId":"POGOProtos\Map\Pokemon\MapPokemon":private]=>
            NULL
            ["pokemonId":"POGOProtos\Map\Pokemon\MapPokemon":private]=>
            int(127)
            ["expirationTimestampMs":"POGOProtos\Map\Pokemon\MapPokemon":private]=>
            int(1469969208412)
            ["latitude":"POGOProtos\Map\Pokemon\MapPokemon":private]=>
            float(-32.0577008121)
            ["longitude":"POGOProtos\Map\Pokemon\MapPokemon":private]=>
            float(115.74406715)
            ["_unknown":"ProtobufMessage":private]=>
            NULL
          }
        }
        ["wildPokemons":"PokemonGoAPI\Api\Map\MapObjects":private]=>
        array(1) {
          [0]=>
          object(POGOProtos\Map\Pokemon\WildPokemon)#573 (9) {
            ["_unknown":"POGOProtos\Map\Pokemon\WildPokemon":private]=>
            NULL
            ["encounterId":"POGOProtos\Map\Pokemon\WildPokemon":private]=>
            NULL
            ["lastModifiedTimestampMs":"POGOProtos\Map\Pokemon\WildPokemon":private]=>
            int(1469969106545)
            ["latitude":"POGOProtos\Map\Pokemon\WildPokemon":private]=>
            float(-32.0577008121)
            ["longitude":"POGOProtos\Map\Pokemon\WildPokemon":private]=>
            float(115.74406715)
            ["spawnPointId":"POGOProtos\Map\Pokemon\WildPokemon":private]=>
            string(11) "2a32a170f4f"
            ["pokemonData":"POGOProtos\Map\Pokemon\WildPokemon":private]=>
            object(POGOProtos\Data\PokemonData)#569 (32) {
              ["_unknown":"POGOProtos\Data\PokemonData":private]=>
              NULL
              ["id":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["pokemonId":"POGOProtos\Data\PokemonData":private]=>
              int(127)
              ["cp":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["stamina":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["staminaMax":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["move1":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["move2":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["deployedFortId":"POGOProtos\Data\PokemonData":private]=>
              string(0) ""
              ["ownerName":"POGOProtos\Data\PokemonData":private]=>
              string(0) ""
              ["isEgg":"POGOProtos\Data\PokemonData":private]=>
              bool(false)
              ["eggKmWalkedTarget":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["eggKmWalkedStart":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["origin":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["heightM":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["weightKg":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["individualAttack":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["individualDefense":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["individualStamina":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["cpMultiplier":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["pokeball":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["capturedCellId":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["battlesAttacked":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["battlesDefended":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["eggIncubatorId":"POGOProtos\Data\PokemonData":private]=>
              string(0) ""
              ["creationTimeMs":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["numUpgrades":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["additionalCpMultiplier":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["favorite":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["nickname":"POGOProtos\Data\PokemonData":private]=>
              string(0) ""
              ["fromFort":"POGOProtos\Data\PokemonData":private]=>
              int(0)
              ["_unknown":"ProtobufMessage":private]=>
              NULL
            }
            ["timeTillHiddenMs":"POGOProtos\Map\Pokemon\WildPokemon":private]=>
            int(101867)
            ["_unknown":"ProtobufMessage":private]=>
            NULL
          }
        }
        ["decimatedSpawnPoints":"PokemonGoAPI\Api\Map\MapObjects":private]=>
        array(0) {
        }
        ["spawnPoints":"PokemonGoAPI\Api\Map\MapObjects":private]=>
        array(4) {
          [0]=>
          object(POGOProtos\Map\SpawnPoint)#237 (4) {
            ["_unknown":"POGOProtos\Map\SpawnPoint":private]=>
            NULL
            ["latitude":"POGOProtos\Map\SpawnPoint":private]=>
            float(-32.0520830374)
            ["longitude":"POGOProtos\Map\SpawnPoint":private]=>
            float(115.745916323)
            ["_unknown":"ProtobufMessage":private]=>
            NULL
          }
          [1]=>
          object(POGOProtos\Map\SpawnPoint)#238 (4) {
            ["_unknown":"POGOProtos\Map\SpawnPoint":private]=>
            NULL
            ["latitude":"POGOProtos\Map\SpawnPoint":private]=>
            float(-32.0519601203)
            ["longitude":"POGOProtos\Map\SpawnPoint":private]=>
            float(115.746101239)
            ["_unknown":"ProtobufMessage":private]=>
            NULL
          }
          [2]=>
          object(POGOProtos\Map\SpawnPoint)#234 (4) {
            ["_unknown":"POGOProtos\Map\SpawnPoint":private]=>
            NULL
            ["latitude":"POGOProtos\Map\SpawnPoint":private]=>
            float(-32.0518572588)
            ["longitude":"POGOProtos\Map\SpawnPoint":private]=>
            float(115.746193698)
            ["_unknown":"ProtobufMessage":private]=>
            NULL
          }
          [3]=>
          object(POGOProtos\Map\SpawnPoint)#235 (4) {
            ["_unknown":"POGOProtos\Map\SpawnPoint":private]=>
            NULL
            ["latitude":"POGOProtos\Map\SpawnPoint":private]=>
            float(-32.0521858988)
            ["longitude":"POGOProtos\Map\SpawnPoint":private]=>
            float(115.745823864)
            ["_unknown":"ProtobufMessage":private]=>
            NULL
          }
        }
        ["gyms":"PokemonGoAPI\Api\Map\MapObjects":private]=>
        array(0) {
        }
        ["pokestops":"PokemonGoAPI\Api\Map\MapObjects":private]=>
        array(0) {
        }
        ["complete":"PokemonGoAPI\Api\Map\MapObjects":private]=>
        bool(true)
      }
      ["mapObjectsExpiry":"PokemonGoAPI\Api\Map\Map":private]=>
      NULL
      ["lastMapUpdate":"PokemonGoAPI\Api\Map\Map":private]=>
      float(1.46996910649E+12)
    }
    ["latitude":"PokemonGoAPI\Api\PokemonGoAPI":private]=>
    float(-32.058087)
    ["longitude":"PokemonGoAPI\Api\PokemonGoAPI":private]=>
    float(115.744325)
    ["altitude":"PokemonGoAPI\Api\PokemonGoAPI":private]=>
    float(0)
    ["output":"PokemonGoAPI\Api\PokemonGoAPI":private]=>
    object(PokemonGoAPI\Utils\Output)#3 (6) {
      ["buffer":"PokemonGoAPI\Utils\Output":private]=>
      string(0) ""
      ["NONE"]=>
      int(0)
      ["INFO"]=>
      int(1)
      ["WARNING"]=>
      int(2)
      ["ERROR"]=>
      int(3)
      ["PK_GO_DEBUG"]=>
      bool(true)
    }`

This is my result everytime for `$map->getCatchablePokemon()` any idea as to why this happens? I still can't get the `encounterId`

**Comment by tuttarealstep** [comment]
Have you updated at the last commit?

**Comment by curt2008** [comment]
Yeah, still appears to be the same

**Comment by curt2008** [comment]
`[05:44:22] We have found 2 Pokemon near you..`
`[05:44:22] 120 is based at -32.0577008121,115.74406715 and has a encounterId of -9146082209273593747`
`[05:44:22] 120 is based at -32.0577008121,115.74406715 and has a encounterId of -9146082209273593747`

`getCatchablePokemon` appears to provide duplicate results

`$catchable = $map->getCatchablePokemon();`
`foreach($catchable as $CatchablePokemon) {`
`echo "[".date("H:i:s")."] ".$CatchablePokemon->getPokemonId()." is based at ".$CatchablePokemon->getLatitude().",".$CatchablePokemon->getLongitude()." and has a encounterId of ".$CatchablePokemon->getEncounterId()."<br/><hr>";`
`}`

**Comment by tuttarealstep** [comment]
Try now after the contribute of akeinhell, if the duplicate bug is fixed.
